apiVersion: v1
kind: Service
metadata:
  name: cygnus
  labels:
    app: cygnus
spec:
  type: ClusterIP
  selector:
    app: cygnus
  ports:
  - port: 5051
    targetPort: cygnus-service
    name: cygnus-service
  - port: 5080
    targetPort: cygnus-api
    name: cygnus-api
