apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
plugin: key-auth
config:
  key_names:
    - Authorization
  key_in_header: true
  key_in_query: false
  key_in_body: false
